### ISSUE TITLE
FrontMatterPreprocessor example -- problem runing it 

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor.org#324]
It's no doubt just me, but I'll be the test case for the unsophisticated user:-)  I tried following `FrontMatterPreprocessor` example  (section 82.1 of the User Manual.  Here is the first try, with the
error in the comments.

_TRY #1_

```
require 'asciidoctor'
require 'asciidoctor/extensions'

# ERROR: te.rb:5:in `block in <main>': uninitialized constant FrontMatterPreprocessor (NameError)

Asciidoctor::Extensions.register do |document|
  preprocessor FrontMatterPreprocessor
end

Asciidoctor.render_file 'sample-with-front-matter.ad', :safe => :safe, :in_place => true
```

Of course!  How could ruby know where `FrontMatterPreprocessor` is?  

@jxxcarlson.noob_rating += 1

So I tried the below: But this time it doesn't know about `preprocessor`.

I tried a few more variants, all unsuccessful.

@jxxcarlson.noob_rating += 1

I must be missing some really simple but really important line of code.

*TRY #2#

```
# file te2.rb
require 'asciidoctor'
require 'asciidoctor/extensions'

# ERROR A: te.rb:5:in `block in <main>': uninitialized constant FrontMatterPreprocessor (NameError)
# ERROR B: te2.rb:31:in `block in <main>': undefined method `preprocessor' for main:Object (NoMethodError)

class FrontMatterPreprocessor < Asciidoctor::Extensions::Preprocessor
  def process reader, lines
    return reader if lines.empty?
    front_matter = []
    if lines.first.chomp == '---'
      original_lines = lines.dup
      lines.shift
      while !lines.empty? && lines.first.chomp != '---'
        front_matter << lines.shift
      end

      if (first = lines.first).nil? || first.chomp != '---'
        lines = original_lines
      else
        lines.shift
        @document.attributes['front-matter'] = front_matter.join.chomp
        # advance the reader by the number of lines taken
        (front_matter.length + 2).times { reader.advance }
      end
    end
    reader
  end
end

Asciidoctor::Extensions.register do |document|
  preprocessor FrontMatterPreprocessor
end

Asciidoctor.render_file 'sample-with-front-matter.ad', :safe => :safe, :in_place => true
```

**Comment by jaredmorgs** [comment]
@mojavelinux said:
> I've updated the section. See if that gets you going.

> Keep in mind that you don't have to run Asciidoctor via the API to load the extensions. You can use the -r flag with the asciidoctor command to require the file that contains the extension register code. The examples in the docs don't reflect that yet.

http://asciidoctor.org/docs/user-manual/#preprocessor-example is where the extra little bit of info about the `-r` flag should go, right? Or should it be applied at the chapter level as a general piece of guidance?

**Comment by mojavelinux** [comment]
I think the -r flag should go at the chapter level (or at the start of the examples section) since it applies to all extension examples. There is now more details about how to do this in the extensions-lab repo. See https://github.com/asciidoctor/asciidoctor-extensions-lab#using-an-extension. I'd say we could include most of that content into the user manual.
